// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBigBUuANgqoI7f5tMBiCjVB2Y6p0Ck9w',
    appId: '1:603340341027:web:e9dcea8ac7514e71181696',
    messagingSenderId: '603340341027',
    projectId: 'hellocity-69f72',
    authDomain: 'hellocity-69f72.firebaseapp.com',
    storageBucket: 'hellocity-69f72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70PEjajqwvyKPGwGCXkRq3yl-HgIJfF0',
    appId: '1:603340341027:android:c7f14343316a1c9b181696',
    messagingSenderId: '603340341027',
    projectId: 'hellocity-69f72',
    storageBucket: 'hellocity-69f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tMy9LGP5VsDFmx8tlEJ3gmuWtaIlhyE',
    appId: '1:603340341027:ios:74b1273847d95add181696',
    messagingSenderId: '603340341027',
    projectId: 'hellocity-69f72',
    storageBucket: 'hellocity-69f72.appspot.com',
    iosClientId: '603340341027-3b0ln6n4i8r9207u53qd80oqcq7s91cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tMy9LGP5VsDFmx8tlEJ3gmuWtaIlhyE',
    appId: '1:603340341027:ios:0c4e1dcb7e73beb6181696',
    messagingSenderId: '603340341027',
    projectId: 'hellocity-69f72',
    storageBucket: 'hellocity-69f72.appspot.com',
    iosClientId: '603340341027-hd7adr45hrbs4v7bbli2dtlrsd6kooqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}